재무 - 재무시스템이해능력 INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '재무시스템이해능력', '조직의 재무시스템과 프로세스를 이해하고 효과적으로 활용하는 역량. 재무 데이터의 흐름과 구조를 파악하여 업무에 적용하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '재무시스템이해능력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 재무시스템의 구조와 기능을 정확히 이해한다\n2. 시스템을 활용하여 필요한 재무정보를 효율적으로 추출한다\n3. 시스템 개선사항을 발견하고 제안한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '재무시스템이해능력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 재무시스템의 구조와 기능을 정확히 이해한다\n2. 시스템을 활용하여 필요한 재무정보를 효율적으로 추출한다\n3. 시스템 개선사항을 발견하고 제안한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '전문지식 보유 및 활용', '해당 분야의 전문지식을 지속적으로 습득하고 실무에 적용하는 역량. 최신 동향과 기법을 파악하여 업무의 질을 향상시키는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '전문지식 보유 및 활용' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 전문분야의 최신 동향과 기법을 지속적으로 학습한다\n2. 전문지식을 실무에 적절히 적용한다\n3. 전문지식을 동료들과 공유하고 확산시킨다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '전문지식 보유 및 활용' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 전문분야의 최신 동향과 기법을 지속적으로 학습한다\n2. 전문지식을 실무에 적절히 적용한다\n3. 전문지식을 동료들과 공유하고 확산시킨다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '고객중심적 사고', '고객의 비즈니스 니즈를 체계적으로 분석하여 체계적으로 이해하는 역량. 고객의 니즈에 맞춰 이를 충족시킬 수 있는 결정적 대안이나 융통성 있게 대응할 수 있는 전략을 설정하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '고객중심적 사고' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 모든 정보의 검토를 바탕으로 한 고객의 니즈를 밝혀내고 우선순위를 정한다\n2. 고객의 니즈를 원가절감 측면이나 효율성 측면에서 충족시켜 줄 수 있는 다양한 방법을 모색한다\n3. 내외부 고객만족 정도를 확인할 수 있는 지표들을 가지고 수시로 만족 여부를 점검한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '고객중심적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 모든 정보의 검토를 바탕으로 한 고객의 니즈를 밝혀내고 우선순위를 정한다\n2. 고객의 니즈를 원가절감 측면이나 효율성 측면에서 충족시켜 줄 수 있는 다양한 방법을 모색한다\n3. 내외부 고객만족 정도를 확인할 수 있는 지표들을 가지고 수시로 만족 여부를 점검한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '프로세스 개선', '기존 업무 프로세스를 분석하여 비효율적인 요소를 발견하고 개선방안을 도출하는 역량. 시스템적 사고를 바탕으로 전체적인 업무 흐름을 최적화하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '프로세스 개선' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 현재 프로세스의 문제점을 체계적으로 분석한다\n2. 개선된 프로세스의 효과를 정량적으로 측정한다\n3. 이해관계자들과의 협의를 통해 개선방안을 실행한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '프로세스 개선' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 현재 프로세스의 문제점을 체계적으로 분석한다\n2. 개선된 프로세스의 효과를 정량적으로 측정한다\n3. 이해관계자들과의 협의를 통해 개선방안을 실행한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '세밀/정확한 일처리', '세세하고 철저하게 개입하여 업무 및 그 결과물을 관리하여 품질수준을 확보하고 정확하게 업무를 처리하는 역량. 업무 목표를 염두에 두면서 세부사항을 정확하고 치밀하게 처리하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '세밀/정확한 일처리' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 각종 정보나 데이터의 정확성을 이중으로 확인한다\n2. 정확성과 관련된 세세한 내용을 매뉴얼화하여 활용한다\n3. 구성원들이 생소한 업무에 처했을 때 정확한 업무처리 프로세스를 찾아 해결할 수 있도록 지원한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '세밀/정확한 일처리' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 각종 정보나 데이터의 정확성을 이중으로 확인한다\n2. 정확성과 관련된 세세한 내용을 매뉴얼화하여 활용한다\n3. 구성원들이 생소한 업무에 처했을 때 정확한 업무처리 프로세스를 찾아 해결할 수 있도록 지원한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '의사결정/판단력', '체계적 논리와 근거에 따라 요구에 맞는 타당한 결론을 내리는 역량. 객관적인 기준, 구체적인 사례, 잦은 의견 교환과 주의깊은 관찰을 통해 객관적 자료와 근거를 중심으로 의사결정을 하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '의사결정/판단력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 결정의 단기 및 장기적 효과를 모두 고려한다\n2. 다양한 이해관계자의 의견을 수렴하여 의사결정한다\n3. 객관적인 데이터와 사실에 근거하여 판단한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '의사결정/판단력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 결정의 단기 및 장기적 효과를 모두 고려한다\n2. 다양한 이해관계자의 의견을 수렴하여 의사결정한다\n3. 객관적인 데이터와 사실에 근거하여 판단한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '주도성', '자발적으로 행동하고 기회를 만들어 새로운 일에 적극적으로 도전하는 역량. 현재 상황에 안주하지 않고 더 나은 결과를 위해 적극적으로 행동하고 변화를 추구하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '주도성' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 업무 개선을 위한 아이디어를 적극적으로 제안한다\n2. 새로운 업무나 프로젝트에 자발적으로 참여한다\n3. 문제 상황에서 해결책을 적극적으로 모색한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '주도성' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 업무 개선을 위한 아이디어를 적극적으로 제안한다\n2. 새로운 업무나 프로젝트에 자발적으로 참여한다\n3. 문제 상황에서 해결책을 적극적으로 모색한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '설득/영향력', '정보, 논리 등을 바탕으로 개인 및 집단을 설득해서 인정을 유도하는 역량. 자기견해, 계획, 아이디어를 수용하도록 타인으로부터 필요한 지지와 지원을 끌어내고 태도나 의견에 영향을 미치는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '설득/영향력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 필요하면 언제나 내외로 움직이면서 스스로의 영향력을 발휘하고 타인을 설득하거나 회유할 수 있다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '설득/영향력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 필요하면 언제나 내외로 움직이면서 스스로의 영향력을 발휘하고 타인을 설득하거나 회유할 수 있다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '설득/영향력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '설득/영향력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '의사결정/판단력', '체계적 논리와 근거에 따라 요구에 맞는 타당한 결론을 내리는 역량. 객관적인 기준, 구체적인 사례, 잦은 의견 교환과 주의깊은 관찰을 통해 객관적 자료와 근거를 중심으로 의사결정을 하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '의사결정/판단력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 의사결정 전에 대안의 장점과 단점을 고려하여 판단의 초점을 명확히 한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '의사결정/판단력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 의사결정 전에 대안의 장점과 단점을 고려하여 판단의 초점을 명확히 한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 실현가능성과 가용성 등의 실제적인 측면에서 의사결정한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '의사결정/판단력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 실현가능성과 가용성 등의 실제적인 측면에서 의사결정한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 시의적절하고 정확한 결정을 내리고 행동방안을 제시한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '의사결정/판단력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 시의적절하고 정확한 결정을 내리고 행동방안을 제시한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '전략적 사고/기획', '내/외부 요인을 장기적이고 포괄적으로 고려하여 문제해결과 의사결정을 하는 역량. 높은 성과를 낼 수 있는 전략을 확인하고 업무 활동 및 프로세스를 체계적으로 계획하고 조직화하여 실행하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '전략적 사고/기획' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 시장 및 경영 환경의 동향을 체계적으로 분석한 결과를 토대로 적합한 대응방안을 제시한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '전략적 사고/기획' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 시장 및 경영 환경의 동향을 체계적으로 분석한 결과를 토대로 적합한 대응방안을 제시한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 핵심 비즈니스 이슈를 구체화하고 조직의 이익 창출을 위한 핵심 성공 요건을 밝힌다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '전략적 사고/기획' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 핵심 비즈니스 이슈를 구체화하고 조직의 이익 창출을 위한 핵심 성공 요건을 밝힌다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 조직 전략 방향에 부합되도록 이해관계자간의 역학 관계를 바탕으로 업무를 조율·조정한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '전략적 사고/기획' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 조직 전략 방향에 부합되도록 이해관계자간의 역학 관계를 바탕으로 업무를 조율·조정한다' );