INSERT INTO competency_models (name, type, description, target_level) SELECT '역량 평가표', 'functional', '직무별 상세 역량 평가 데이터 (감사/기획, 마케팅, 영업, 인사, 재경, 법무, 홍보 등)', 'all' WHERE NOT EXISTS (SELECT 1 FROM competency_models WHERE name = '역량 평가표');

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '분석적 사고', '타당한 정보를 근거로 논리 정연하게 사고하여 정확하고 의미 있는 결론을 도출하는 역량. 정보를 체계적으로 분석하여 핵심 요소, 상호 연관성, 경향성을 파악해 상황판단, 문제해결, 의사결정 등에 활용하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '분석적 사고' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 구체적인 정보와 사실에 주의를 기울여 정보의 정확성을 판단한다\n2. 문제발생시 근본 원인을 세밀히 파악한다\n3. 사안을 다각도로 분석하여 정리한다(예, 비용, 리스크, 필요자원 및 기술 등)\n4. 수집된 정보의 분석 결과를 토대로 현상을 정확히 반영한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '분석적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 구체적인 정보와 사실에 주의를 기울여 정보의 정확성을 판단한다\n2. 문제발생시 근본 원인을 세밀히 파악한다\n3. 사안을 다각도로 분석하여 정리한다(예, 비용, 리스크, 필요자원 및 기술 등)\n4. 수집된 정보의 분석 결과를 토대로 현상을 정확히 반영한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '의사결정/판단력', '체계적 논리와 근거에 따라 요구에 맞는 타당한 결론을 내리는 역량. 객관적인 기준, 구체적인 사례, 잦은 의견 교환과 주의깊은 관찰을 통해 객관적 자료와 근거를 중심으로 의사결정을 하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '의사결정/판단력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 결정의 단기 및 장기적 효과를 모두 고려한다\n2. 의사결정이 미치는 조직구조, 프로세스, 구성원들의 태도 등을 포괄적이고 면밀하게 검토한다\n3. 객관적인 정보와 사실에 입각해서 의사결정한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '의사결정/판단력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 결정의 단기 및 장기적 효과를 모두 고려한다\n2. 의사결정이 미치는 조직구조, 프로세스, 구성원들의 태도 등을 포괄적이고 면밀하게 검토한다\n3. 객관적인 정보와 사실에 입각해서 의사결정한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '전략적 사고/기획', '내/외부 요인을 장기적이고 포괄적으로 고려하여 문제해결과 의사결정을 하는 역량. 높은 성과를 낼 수 있는 전략을 확인하고 업무 활동 및 프로세스를 체계적으로 계획하고 조직화하여 실행하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '전략적 사고/기획' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 계획 실행 시 조직에 미칠 영향력이나 장기적 관점에서 큰 그림을 그린다\n2. 조직 전략 방향에 부합되도록 부서/팀/구성원간의 역학 관계를 바탕으로 업무 계획을 조율·조정한다\n3. 수집된 정보의 분석 결과를 토대로 현상을 정확히 반영한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '전략적 사고/기획' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 계획 실행 시 조직에 미칠 영향력이나 장기적 관점에서 큰 그림을 그린다\n2. 조직 전략 방향에 부합되도록 부서/팀/구성원간의 역학 관계를 바탕으로 업무 계획을 조율·조정한다\n3. 수집된 정보의 분석 결과를 토대로 현상을 정확히 반영한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '창의적 사고', '관련성이 적은 개념들 속에서 새롭고 독창적인 연계성을 파악해 가치 있는 아이디어를 창출하는 역량. 목표 달성을 위해 새로운 아이디어와 개념을 적용하여 변화를 시도하거나 창의적인 해결안을 도출하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '창의적 사고' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 창의적 아이디어를 사업적인 기회로 전환하여 제시한다\n2. 실험적 정신으로 새로운 방법과 접근식 방식으로 업무를 수행한다\n3. 문제나 상황을 다양한 시각에서 본다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '창의적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 창의적 아이디어를 사업적인 기회로 전환하여 제시한다\n2. 실험적 정신으로 새로운 방법과 접근식 방식으로 업무를 수행한다\n3. 문제나 상황을 다양한 시각에서 본다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '설득/영향력', '정보, 논리 등을 바탕으로 개인 및 집단을 설득해서 동의와 이해를 얻어내는 역량. 자기견해, 계획, 아이디어를 수용하도록 타인으로부터 필요한 지지와 지원을 끌어내고 태도나 의견을 유도하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '설득/영향력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다\n2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다\n3. 질문과 저항을 예상하고 준비한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '설득/영향력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다\n2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다\n3. 질문과 저항을 예상하고 준비한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '팀웍/협동', '공통의 목표 달성을 위해 타인과 협조하는 역량. 개인적 관심사보다 팀 목표를 우선시하고, 최종 결과에 대한 팀/부서의 공동책임을 상호 이해하고 공유하여 협조하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '팀웍/협동' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 어떤 결정을 내리거나 계획을 세울 때 아이디어와 의견을 구하고 수렴한다\n2. 팀 구성원들의 다양한 개성을 인정하고 최대한 활용한다\n3. 타 부서의 협조요청에 적극적으로 임한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '팀웍/협동' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 어떤 결정을 내리거나 계획을 세울 때 아이디어와 의견을 구하고 수렴한다\n2. 팀 구성원들의 다양한 개성을 인정하고 최대한 활용한다\n3. 타 부서의 협조요청에 적극적으로 임한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '프로젝트 관리', '프로젝트의 범위 및 산출물을 정의하고, 효과적 프로세스를 설계하고 실행하는 역량. 우선순위와 시간, 그리고 자원을 효율적으로 배분 관리하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '프로젝트 관리' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 프로젝트와 관련된 장애요인 및 핵심이슈를 파악하여 극복대안을 설계 실행한다\n2. 프로젝트 수행을 위한 인적, 물적 자원의 특징을 파악하고 이를 효과적으로 배분한다\n3. 핵심 이해관계자와 범위 및 산출에 대해 동일한 시각을 형성하고, 이들의 관심사항을 정확히 이해한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '프로젝트 관리' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 프로젝트와 관련된 장애요인 및 핵심이슈를 파악하여 극복대안을 설계 실행한다\n2. 프로젝트 수행을 위한 인적, 물적 자원의 특징을 파악하고 이를 효과적으로 배분한다\n3. 핵심 이해관계자와 범위 및 산출에 대해 동일한 시각을 형성하고, 이들의 관심사항을 정확히 이해한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '관계형성', '장/단기적 비즈니스 프로세스 및 성과를 향상시키기 위해 고객, 공급자, 협력자 등 중요한 관련 주체들과의 관계를 형성하고 상호 간 신뢰를 구축하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '관계형성' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 조직의 지속적인 성과창출과 이미지 향상에 필요한 네트워크를 발굴하고 활용함\n2. 조직에 영향을 미치는 다양한 관계 집단과의 우호적인 관계를 유지함\n3. 공식적인 관계 외에도 업무수행에 도움이 되는 비공식적인 관계를 수립함', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '관계형성' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 조직의 지속적인 성과창출과 이미지 향상에 필요한 네트워크를 발굴하고 활용함\n2. 조직에 영향을 미치는 다양한 관계 집단과의 우호적인 관계를 유지함\n3. 공식적인 관계 외에도 업무수행에 도움이 되는 비공식적인 관계를 수립함' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '문서작성 및 관리', '보고서나 전달하고자 하는 지식 및 정보를 문서로 체계적으로 표현하며 향후 업무수행에 용이하게 활용하기 위하여 이를 관리하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '문서작성 및 관리' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 복잡한 서면정보를 이해하고 해석하여 필요한 사항만을 논리적으로 간결하게 작성하며 설득력 있는 주장을 위해서 필요한 자료를 준비함\n2. 필요에 따라 숫자를 문장화 또는 문자를 도식화하여 문서를 작성함\n3. 문서를 보고 정보를 얻으려는 사람들이 가장 쉽게 이해할 수 있도록 문서를 작성함', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '문서작성 및 관리' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 복잡한 서면정보를 이해하고 해석하여 필요한 사항만을 논리적으로 간결하게 작성하며 설득력 있는 주장을 위해서 필요한 자료를 준비함\n2. 필요에 따라 숫자를 문장화 또는 문자를 도식화하여 문서를 작성함\n3. 문서를 보고 정보를 얻으려는 사람들이 가장 쉽게 이해할 수 있도록 문서를 작성함' );