영업 - 고객중심적 사고 INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '고객중심적 사고', '고객의 비즈니스 니즈를 체계적으로 분석하여 체계적으로 이해하는 역량. 고객의 니즈에 맞춰 이를 충족시킬 수 있는 결정적 대안이나 융통성 있게 대응할 수 있는 전략을 설정하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '고객중심적 사고' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 고객의 니즈를 정확히 이해해 고객에게 높은 가치를 제공하는 솔루션을 개발한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '고객중심적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 고객의 니즈를 정확히 이해해 고객에게 높은 가치를 제공하는 솔루션을 개발한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 고객과의 지속적인 관계 유지를 위해 적극적으로 노력한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '고객중심적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 고객과의 지속적인 관계 유지를 위해 적극적으로 노력한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 고객 만족도 향상을 위한 개선 방안을 지속적으로 모색한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '고객중심적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 고객 만족도 향상을 위한 개선 방안을 지속적으로 모색한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '관계형성', '고객, 동료, 협력업체 등 중요한 관련 주체들과의 관계를 형성하고 상호간 신뢰를 구축하는 역량. 장기적 비즈니스 성과 향상에 필요한 네트워크를 발굴하고 활용하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '관계형성' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 다양한 이해관계자와 원활한 관계를 구축하고 유지한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '관계형성' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 다양한 이해관계자와 원활한 관계를 구축하고 유지한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 신뢰를 바탕으로 한 장기적 파트너십을 형성한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '관계형성' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 신뢰를 바탕으로 한 장기적 파트너십을 형성한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 네트워킹 활동을 통해 비즈니스 기회를 창출한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '관계형성' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 네트워킹 활동을 통해 비즈니스 기회를 창출한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '서비스 지향', '고객의 요구를 우선적으로 감안하고, 고객 만족을 위해서 최선을 다하는 자세. 고객 요청이 있는 경우, 적극적으로 경청하여 요구사항을 정확히 파악하여 직접적인 도움이 될 수 있는 양질의 서비스를 제공하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '서비스 지향' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 고객의 요구사항에 가장 효과적인 대응 방안을 수립한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '서비스 지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 고객의 요구사항에 가장 효과적인 대응 방안을 수립한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 고객에게 신속하고 정확한 서비스를 제공한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '서비스 지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 고객에게 신속하고 정확한 서비스를 제공한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 고객 불만을 사전에 예방하고 발생시 즉시 해결한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '서비스 지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 고객 불만을 사전에 예방하고 발생시 즉시 해결한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '성과지향', '목표한 성과를 달성하기 위해 지속적으로 노력하고 결과에 대한 책임을 지는 역량. 높은 목표를 설정하고 이를 달성하기 위한 전략과 실행력을 발휘하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '성과지향' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 명확하고 도전적인 목표를 설정한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '성과지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 명확하고 도전적인 목표를 설정한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '2. 목표 달성을 위한 구체적인 실행 계획을 수립하고 추진한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '성과지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '2. 목표 달성을 위한 구체적인 실행 계획을 수립하고 추진한다' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '3. 성과 결과에 대해 책임감을 갖고 지속적으로 개선한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '성과지향' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '3. 성과 결과에 대해 책임감을 갖고 지속적으로 개선한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '상황판단 및 대처능력', '다양한 상황에서 적절한 판단을 내리고 효과적으로 대처하는 역량. 예상치 못한 상황이나 위기 상황에서도 신속하고 정확한 판단으로 적절히 대응하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '상황판단 및 대처능력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 상황의 긴급성과 중요성을 정확히 판단한다\n2. 제한된 정보 하에서도 합리적인 의사결정을 내린다\n3. 위기 상황에서 침착하게 대응방안을 수립하고 실행한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '상황판단 및 대처능력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 상황의 긴급성과 중요성을 정확히 판단한다\n2. 제한된 정보 하에서도 합리적인 의사결정을 내린다\n3. 위기 상황에서 침착하게 대응방안을 수립하고 실행한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '동시다중업무수행', '다양한 업무를 동시에 수행하면서 업무의 진척도와 품질을 유지하는 역량. 여러 상황적 요인으로 인해 새로운 업무가 부과되더라도 기존 업무를 효과적으로 조정하여 새로운 업무를 동시에 처리하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '동시다중업무수행' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 업무 진행 과정에 대해 효율적으로 모니터링 하여 진척 상황 및 결과를 체크한다\n2. 아웃소싱이나 업무 협조를 효과적으로 활용하여 직접 업무수행을 최소화하고 이들을 효과적으로 관리 모니터링한다\n3. 업무의 우선순위 및 시간할당을 정확하게 관리한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '동시다중업무수행' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 업무 진행 과정에 대해 효율적으로 모니터링 하여 진척 상황 및 결과를 체크한다\n2. 아웃소싱이나 업무 협조를 효과적으로 활용하여 직접 업무수행을 최소화하고 이들을 효과적으로 관리 모니터링한다\n3. 업무의 우선순위 및 시간할당을 정확하게 관리한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '변화관리/주도', '조직의 변화를 주도적으로 이끌어가고 구성원들이 변화에 적응할 수 있도록 지원하는 역량. 변화의 필요성을 인식하고 변화 추진 과정에서 발생하는 저항을 효과적으로 관리하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '변화관리/주도' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 조직 변화의 필요성을 명확히 인식하고 전파한다\n2. 변화 과정에서 구성원들의 저항을 이해하고 적절히 대응한다\n3. 변화 목표와 방향을 구체적으로 설정하고 실행한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '변화관리/주도' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 조직 변화의 필요성을 명확히 인식하고 전파한다\n2. 변화 과정에서 구성원들의 저항을 이해하고 적절히 대응한다\n3. 변화 목표와 방향을 구체적으로 설정하고 실행한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '설득/영향력', '정보, 논리 등을 바탕으로 개인 및 집단을 설득해서 동의와 이해를 얻어내는 역량. 자기견해, 계획, 아이디어를 수용하도록 타인으로부터 필요한 지지와 지원을 끌어내고 태도나 의견을 유도하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '설득/영향력' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다\n2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다\n3. 질문과 저항을 예상하고 준비한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '설득/영향력' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 상대로 하여금 유익한 점을 보도록 유도함으로써 동의와 이해를 얻어낸다\n2. 자신이 주장하고자 하는 내용과 상대의 관심사를 정확히 이해한다\n3. 질문과 저항을 예상하고 준비한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '분석적 사고', '타당한 정보를 근거로 논리 정연하게 사고하여 정확하고 의미 있는 결론을 도출하는 역량. 정보를 체계적으로 분석하여 핵심 요소, 상호 연관성, 경향성을 파악해 상황판단, 문제해결, 의사결정 등에 활용하는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '분석적 사고' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 재무 데이터를 체계적으로 분석하여 경영상 시사점을 도출한다\n2. 복잡한 재무 현상을 핵심 요소별로 분해하여 이해한다\n3. 과거 데이터의 경향성을 분석하여 미래 예측에 활용한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '분석적 사고' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 재무 데이터를 체계적으로 분석하여 경영상 시사점을 도출한다\n2. 복잡한 재무 현상을 핵심 요소별로 분해하여 이해한다\n3. 과거 데이터의 경향성을 분석하여 미래 예측에 활용한다' );

INSERT INTO competencies (model_id, keyword, description) SELECT m.id, '손익마인드', '투입 대비 산출과 비용의 경제성을 기초로 손익을 관리하는 역량. 비용 대비 효과성이 뛰어난 상품이나 서비스의 개발, 손익 구조 개선 등 이윤 창출의 기회를 파악해 내는 역량' FROM competency_models m WHERE m.name = '역량 평가표' AND NOT EXISTS ( SELECT 1 FROM competencies c WHERE c.model_id = m.id AND c.keyword = '손익마인드' );

INSERT INTO behavioral_indicators (competency_id, indicator_text, level) SELECT c.id, '1. 불확실한 상황에서 정확한 의사결정으로 이익을 창출한다\n2. 비용대비 효과성을 중요하게 여긴다\n3. 사업비 절감 및 손익구조 개선을 위한 방안을 수립한다', 'general' FROM competencies c JOIN competency_models m ON c.model_id = m.id WHERE m.name = '역량 평가표' AND c.keyword = '손익마인드' AND NOT EXISTS ( SELECT 1 FROM behavioral_indicators bi WHERE bi.competency_id = c.id AND bi.indicator_text = '1. 불확실한 상황에서 정확한 의사결정으로 이익을 창출한다\n2. 비용대비 효과성을 중요하게 여긴다\n3. 사업비 절감 및 손익구조 개선을 위한 방안을 수립한다' );